### ISSUE TITLE
NixOS module ?

### ISSUE THREAD

**Issue by drupol** [jbuchermn/guacamole-nixos#3]
Hello again,

Do you plan to make a PR providing the NixOS module?

Thanks!

**Comment by jbuchermn** [comment]
Hi,

yes, I plan on doing that. Before submitting a PR, I think we need to add missing configuration options and maybe clean up the nixos module interface.

At first I'll take a look into enabling extension jars in the client.

What do you think is necessary for a PR?

**Comment by drupol** [comment]
Great, count on my to test the thing and to help if needed !

**Comment by drupol** [comment]
Fixed in https://github.com/NixOS/nixpkgs/pull/237824

I think we can now delete this repository, the upstream version has been merged and includes improved modules.

**Comment by jbuchermn** [comment]
Thanks a lot for your work on this. Sorry it took me so long

**Comment by drupol** [comment]
It's totally fine, I needed it :)

There are still work to do if you want, it would be nice to have options to enable the different authentication and  handle extensions.

**Comment by jbuchermn** [comment]
Alright I'll leave this issue open then and work on it when I find some free time

**Comment by jbuchermn** [comment]
Closing at as it looks like I'm never finding time for it
